/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package consultas.views;

import consultas.Database;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Meltsan
 */
public class altaEmployees extends javax.swing.JFrame {
    int bandEdit=0;//bandera que se activa cuando se presiona el boton de editar    
    Database d;    
    /**
     * Creates new form altaEmployees
     */
    public altaEmployees() {
        initComponents();
        lblTitulo.setText("ALTA DE EMPLEADO");
        this.d = new Database();
    }
    public altaEmployees(String id,String fName, String lName, String email,String phone, String hDate,
                String jobId, String salary, String commision, String mngId, String depId) {
        initComponents();
        campo1.setText(id);
        campo2.setText(fName);
        campo3.setText(lName);
        campo4.setText(email);
        campo5.setText(phone);
        campo6.setText(hDate);
        campo7.setText(jobId);
        campo8.setText(salary);
        campo9.setText(commision);
        campo10.setText(mngId);
        campo11.setText(depId);
        
        campo1.setEditable(false);
        campo7.setEditable(false);
        campo10.setEditable(false);
        campo11.setEditable(false);
        lblTitulo.setText("EDITAR EMPLEADO");
        this.bandEdit=1;
        this.d = new Database();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campo1 = new javax.swing.JTextField();
        campo2 = new javax.swing.JTextField();
        campo3 = new javax.swing.JTextField();
        campo4 = new javax.swing.JTextField();
        campo5 = new javax.swing.JTextField();
        campo7 = new javax.swing.JTextField();
        campo8 = new javax.swing.JTextField();
        campo9 = new javax.swing.JTextField();
        campo10 = new javax.swing.JTextField();
        campo11 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        campo6 = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(campo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 177, 30));
        getContentPane().add(campo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 177, 30));
        getContentPane().add(campo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 177, 30));
        getContentPane().add(campo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 177, 30));
        getContentPane().add(campo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 177, 30));
        getContentPane().add(campo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 177, 30));
        getContentPane().add(campo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 177, 30));
        getContentPane().add(campo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 177, 30));
        getContentPane().add(campo10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 177, 30));
        getContentPane().add(campo11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 177, 30));

        jLabel1.setText("ID DEL EMPLEADO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jLabel2.setText("NOMBRE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel3.setText("APELLIDO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jLabel4.setText("CORREO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jLabel5.setText("NÚMERO DE TELÉFONO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        jLabel6.setText("FECHA DE CONTRATACIÓN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        jLabel7.setText("ID DEL EMPLEO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        jLabel8.setText("SALARIO");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        jLabel9.setText("PORCENTAJE DE COMISIÓN");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, -1));

        jLabel10.setText("ID DE ADMINISTRADOR");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, -1, -1));

        jLabel11.setText("ID DE DEPARTAMENTO");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, -1, -1));

        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 590, -1, -1));

        lblTitulo.setText("----");
        lblTitulo.setToolTipText("");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        campo6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        getContentPane().add(campo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 180, 30));

        jLabel12.setText("dd/mm/yyyy");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(bandEdit==1){
                if(d.conectar()){
                    int id = Integer.parseInt(campo1.getText());
                    String fName = campo2.getText();
                    String lName= campo3.getText();
                    String email = campo4.getText();
                    String phone= campo5.getText();
                    String hDate = campo6.getText();
                    float salary = Float.parseFloat(campo8.getText());
                    float commision = Float.parseFloat(campo9.getText());
                    if (d.actualizarEmployee(id, fName, lName, email, phone, hDate, salary, commision)){
                       JOptionPane.showMessageDialog(null,"Actualización correcta");
                       limpiarCajas();
                    }else{
                        JOptionPane.showMessageDialog(null,"ERROR !!! NO SE PUDO LLEVAR A CABO LA ACUTALIZACIÓN");
                    }
                }
		else
                    System.out.println("No se pudo conectar. Revisa los datos introducidos.");
        }else{
            
                if(d.conectar()){
                    int id = Integer.parseInt(campo1.getText());
                    String fName = campo2.getText();
                    String lName= campo3.getText();
                    String email = campo4.getText();
                    String phone= campo5.getText();
                    String hDate = campo6.getText();
                    String jobId = campo7.getText();
                    float salary = Float.parseFloat(campo8.getText());
                    float commision = Float.parseFloat(campo9.getText());
                    int managerId = Integer.parseInt(campo10.getText());
                    int deptoId = Integer.parseInt(campo11.getText());
                    if (d.insertarEmployee(id, fName, lName, email, phone, hDate,jobId, salary, commision, managerId, deptoId)){
                       JOptionPane.showMessageDialog(null,"Inserción correcta");
                       limpiarCajas();
                    }else{
                        JOptionPane.showMessageDialog(null,"ERROR !!! NO SE PUDO LLEVAR A CABO LA INSERCION");
                    }
                }
		else
                    System.out.println("No se pudo conectar. Revisa los datos introducidos.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void limpiarCajas(){
        campo1.setText("");
        campo2.setText("");
        campo3.setText("");
        campo4.setText("");
        campo5.setText("");
        campo6.setText("");
        campo7.setText("");
        campo8.setText("");
        campo9.setText("");
        campo10.setText("");
        campo11.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(altaEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(altaEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(altaEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(altaEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new altaEmployees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campo1;
    private javax.swing.JTextField campo10;
    private javax.swing.JTextField campo11;
    private javax.swing.JTextField campo2;
    private javax.swing.JTextField campo3;
    private javax.swing.JTextField campo4;
    private javax.swing.JTextField campo5;
    private javax.swing.JFormattedTextField campo6;
    private javax.swing.JTextField campo7;
    private javax.swing.JTextField campo8;
    private javax.swing.JTextField campo9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
