/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package consultas.views;

import consultas.Database;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Meltsan
 */
public class employees extends javax.swing.JFrame {
    DefaultTableModel modelo;
    Database d;
    ResultSet rs;
    /**
     * Creates new form departments
     */
    public employees() throws SQLException {
        initComponents();
        cargarDatos();
    }
public void cargarDatos() throws SQLException{
            modelo= new DefaultTableModel();        
            //modelo.addColumn("Número Adquisición");
            modelo.addColumn("EMPLOYEE_ID");
            modelo.addColumn("FIRST_NAME");
            modelo.addColumn("LAST_NAME"); 
            modelo.addColumn("EMAIL"); 
            modelo.addColumn("PHONE_NUMBER");
            modelo.addColumn("HIRE_DATE");
            modelo.addColumn("JOB_ID"); 
            modelo.addColumn("SALARY"); 
            modelo.addColumn("COMMISSION_PCT");
            modelo.addColumn("MANAGER_ID");
            modelo.addColumn("DEPARTMENT_ID");             
            jTable1.setModel(modelo);  
            
            String []Datos= new String[11];
            
		Database d=new Database();
                
		System.out.println("Conectando con la base de datos:");
		if(d.conectar()){
			rs=d.ejecutarConsulta("select * from employees @LINK_B");
                        while(rs.next()) {
				for(int i=1; i<=11; i++) {
					Datos[i-1]=rs.getString(i);
				}
                                modelo.addRow(Datos);
                        }
                }
		else
			System.out.println("No se pudo conectar. Revisa los datos introducidos.");

                rs=d.ejecutarConsulta("select city from LOCATIONS@LINK_C");
    
                while(rs.next()){
                    jComboLocation.addItem((String) rs.getObject(1));
                }
                
		if(d.desconectar())
			System.out.println("Desconectado tras jecutar la consulta.");
		else
			System.out.println("Por alguna razón no se ha podido desconectar.");            
                
}

public void cargarDatos(String categoria, String parametro) throws SQLException{
            modelo= new DefaultTableModel();        
            //modelo.addColumn("Número Adquisición");
            modelo.addColumn("EMPLOYEE_ID");
            modelo.addColumn("FIRST_NAME");
            modelo.addColumn("LAST_NAME"); 
            modelo.addColumn("EMAIL"); 
            modelo.addColumn("PHONE_NUMBER");
            modelo.addColumn("HIRE_DATE");
            modelo.addColumn("JOB_ID"); 
            modelo.addColumn("SALARY"); 
            modelo.addColumn("COMMISSION_PCT");
            modelo.addColumn("MANAGER_ID");
            modelo.addColumn("DEPARTMENT_ID");             
            jTable1.setModel(modelo);  
            
            String []Datos= new String[11];
            
		Database d=new Database();
                
		System.out.println("Conectando con la base de datos:");
                String consulta = "select * from employees@LINK_B where "+categoria+" LIKE '%"+parametro+"%'";
                System.out.println(consulta);
		if(d.conectar()){
			this.rs=d.ejecutarConsulta(consulta);
                        while(rs.next()) {
				for(int i=1; i<=11; i++) {
					Datos[i-1]=rs.getString(i);
				}
                                modelo.addRow(Datos);
                        }
                }
		else
			System.out.println("No se pudo conectar. Revisa los datos introducidos.");
		if(d.desconectar())
			System.out.println("Desconectado tras jecutar la consulta.");
		else
			System.out.println("Por alguna razón no se ha podido desconectar.");            
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxCat = new javax.swing.JComboBox<>();
        jTextFieldParam = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnVerTodo = new javax.swing.JButton();
        jComboLocation = new javax.swing.JComboBox<>();
        jButEmpleados = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Departamentos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Book", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("EMPLEADOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 900, 280));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("UBICACIÓN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, 30));

        jComboBoxCat.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        jComboBoxCat.setForeground(new java.awt.Color(204, 0, 0));
        jComboBoxCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "EMPLOYEE_ID", "FIRST_NAME", "LAST_NAME", "EMAIL", "PHONE_NUMBER", "HIRE_DATE", "JOB_ID", "SALARY", "COMMISSION_PCT", "MANAGER_ID", "DEPARTMENT_ID" }));
        getContentPane().add(jComboBoxCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 180, -1));

        jTextFieldParam.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        jTextFieldParam.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(jTextFieldParam, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 150, 30));

        btnBuscar.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(204, 0, 0));
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, -1, 30));

        btnVerTodo.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        btnVerTodo.setForeground(new java.awt.Color(204, 0, 0));
        btnVerTodo.setText("VER TODOS");
        btnVerTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTodoActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, -1, 30));

        jComboLocation.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        jComboLocation.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(jComboLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 200, 30));

        jButEmpleados.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        jButEmpleados.setForeground(new java.awt.Color(204, 0, 0));
        jButEmpleados.setText("ID y nombre empleados");
        jButEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEmpleadosActionPerformed(evt);
            }
        });
        getContentPane().add(jButEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 270, 40));

        jButton4.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 0, 0));
        jButton4.setText("ID y nombre departamento");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 290, 40));

        jButton5.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(204, 0, 0));
        jButton5.setText("ID y nombre ubicacion");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 250, 40));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("BUSCAR POR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, 30));

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/consultas/views/fondo1.jpg"))); // NOI18N
        getContentPane().add(lbl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String categoria = (String) jComboBoxCat.getSelectedItem();
        String parametro = jTextFieldParam.getText();
        System.out.println(categoria);
        if(!categoria.equals("SELECCIONE")){
            if(!"".equals(jTextFieldParam.getText())){
                try {
                    cargarDatos(categoria, parametro);
                } catch (SQLException ex) {
                    Logger.getLogger(countries.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Par favar escribe un parametro de busqueda");
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Par favar seleccione una categoria");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnVerTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTodoActionPerformed
        try {
            cargarDatos();
        } catch (SQLException ex) {
            Logger.getLogger(countries.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVerTodoActionPerformed

    private void jButEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEmpleadosActionPerformed
        // TODO add your handling code here:}
        Database d=new Database();
        System.out.println("Conectando con la base de datos:");
        if(d.conectar())
        try {
            rs=d.ejecutarConsulta("select employees.employee_id , employees.first_name, employees.last_name from employees@LINK_B , departments@LINK_B, locations@LINK_C"
                    + " where locations.location_id = departments.location_id and departments.department_id = employees.department_id and locations.city = '"+jComboLocation.getSelectedItem()+"'");
        } catch (SQLException ex) {
            Logger.getLogger(employees.class.getName()).log(Level.SEVERE, null, ex);
        }
        else
        System.out.println("No se pudo conectar. Revisa los datos introducidos.");

        String [] titulos ={"ID empleados","Primer apellido", "Segundo apellido"};

        modelo=new DefaultTableModel(null, titulos);

        String fila []= new String [3];

        try {
            while(rs.next()){
                fila [0]=rs.getString("EMPLOYEE_ID");
                fila [1]=rs.getString("FIRST_NAME");
                fila [2]=rs.getString("LAST_NAME");
                modelo.addRow(fila);

            }
        } catch (SQLException ex) {
            Logger.getLogger(employees.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTable1.setModel(modelo);
    }//GEN-LAST:event_jButEmpleadosActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Database d=new Database();
        System.out.println("Conectando con la base de datos:");
        if(d.conectar())
        try {
            rs=d.ejecutarConsulta("select departments.department_id , departments.department_name from  departments@LINK_B, locations@LINK_C where locations.location_id = departments.location_id  and locations.city = '"+jComboLocation.getSelectedItem()+"'");
        } catch (SQLException ex) {
            Logger.getLogger(employees.class.getName()).log(Level.SEVERE, null, ex);
        }
        else
        System.out.println("No se pudo conectar. Revisa los datos introducidos.");

        String [] titulos ={"ID departamento","Nombre del departamento"};

        modelo=new DefaultTableModel(null, titulos);

        String fila []= new String [2];

        try {
            while(rs.next()){
                fila [0]=rs.getString("DEPARTMENT_ID");
                fila [1]=rs.getString("DEPARTMENT_NAME");
                modelo.addRow(fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(employees.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTable1.setModel(modelo);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Database d=new Database();
        System.out.println("Conectando con la base de datos:");
        if(d.conectar())
        try {
            rs=d.ejecutarConsulta("select location_id , city from   locations@LINK_C where city ='"+jComboLocation.getSelectedItem()+"'");
        } catch (SQLException ex) {
            Logger.getLogger(employees.class.getName()).log(Level.SEVERE, null, ex);
        }
        else
        System.out.println("No se pudo conectar. Revisa los datos introducidos.");

        String [] titulos ={"ID ubicación","Ciudad"};

        modelo=new DefaultTableModel(null, titulos);

        String fila []= new String [2];

        try {
            while(rs.next()){
                fila [0]=rs.getString("LOCATION_ID");
                fila [1]=rs.getString("CITY");
                modelo.addRow(fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(employees.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTable1.setModel(modelo);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new employees().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(employees.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnVerTodo;
    private javax.swing.JButton jButEmpleados;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBoxCat;
    private javax.swing.JComboBox<String> jComboLocation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldParam;
    private javax.swing.JLabel lbl_fondo;
    // End of variables declaration//GEN-END:variables
}
